<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VpsPlanSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data
        DB::table('vps_plans')->delete();

        $now = now();

        $plans = [
            // VPS 2026 - Regular VPS (2.5x OVH pricing)
            [
                'name' => 'VPS-1',
                'slug' => 'vps-1',
                'category' => 'vps_2026',
                'display_name' => 'VPS-1 - Entry Level',
                'description' => 'Perfect for small websites and development projects',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 75,
                'disk_type' => 'SSD',
                'bandwidth' => '400 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 1400.00,
                'cost_price' => 560.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '75 GB SSD', 'Daily backup', 'Unlimited traffic', '400 Mbps bandwidth']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'VPS-2',
                'slug' => 'vps-2',
                'category' => 'vps_2026',
                'display_name' => 'VPS-2 - Standard',
                'description' => 'Ideal for growing businesses and applications',
                'cpu_cores' => 6,
                'memory_gb' => 12,
                'disk_gb' => 100,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 2153.00,
                'cost_price' => 861.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['6 vCores', '12 GB RAM', '100 GB NVMe', 'Daily backup', 'Unlimited traffic', '1 Gbps bandwidth']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'VPS-3',
                'slug' => 'vps-3',
                'category' => 'vps_2026',
                'display_name' => 'VPS-3 - Recommended',
                'description' => 'Best value for performance and resources',
                'cpu_cores' => 8,
                'memory_gb' => 24,
                'disk_gb' => 200,
                'disk_type' => 'NVMe',
                'bandwidth' => '1.5 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 4308.00,
                'cost_price' => 1723.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '24 GB RAM', '200 GB NVMe', 'Daily backup', 'Unlimited traffic', '1.5 Gbps bandwidth']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'VPS-4',
                'slug' => 'vps-4',
                'category' => 'vps_2026',
                'display_name' => 'VPS-4 - Advanced',
                'description' => 'High performance for demanding applications',
                'cpu_cores' => 16,
                'memory_gb' => 48,
                'disk_gb' => 300,
                'disk_type' => 'NVMe',
                'bandwidth' => '2 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 7970.00,
                'cost_price' => 3188.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['16 vCores', '48 GB RAM', '300 GB NVMe', 'Daily backup', 'Unlimited traffic', '2 Gbps bandwidth']),
                'is_active' => true,
                'is_sold_out' => true,
                'is_recommended' => false,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'VPS-5',
                'slug' => 'vps-5',
                'category' => 'vps_2026',
                'display_name' => 'VPS-5 - Enterprise',
                'description' => 'Maximum power for enterprise workloads',
                'cpu_cores' => 24,
                'memory_gb' => 64,
                'disk_gb' => 350,
                'disk_type' => 'NVMe',
                'bandwidth' => '2.5 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 11850.00,
                'cost_price' => 4740.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['24 vCores', '64 GB RAM', '350 GB NVMe', 'Daily backup', 'Unlimited traffic', '2.5 Gbps bandwidth']),
                'is_active' => true,
                'is_sold_out' => true,
                'is_recommended' => false,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'VPS-6',
                'slug' => 'vps-6',
                'category' => 'vps_2026',
                'display_name' => 'VPS-6 - Ultimate',
                'description' => 'Ultimate performance for critical systems',
                'cpu_cores' => 32,
                'memory_gb' => 96,
                'disk_gb' => 400,
                'disk_type' => 'NVMe',
                'bandwidth' => '3 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 15730.00,
                'cost_price' => 6292.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['32 vCores', '96 GB RAM', '400 GB NVMe', 'Daily backup', 'Unlimited traffic', '3 Gbps bandwidth']),
                'is_active' => true,
                'is_sold_out' => true,
                'is_recommended' => false,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // n8n VPS - Automation focused (2.5x pricing)
            [
                'name' => 'n8n-Starter',
                'slug' => 'n8n-starter',
                'category' => 'n8n',
                'display_name' => 'n8n VPS Starter',
                'description' => 'Perfect for workflow automation beginners. Pre-installed n8n with 1,000 executions/month.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 80,
                'disk_type' => 'NVMe',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 1750.00,
                'cost_price' => 700.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '80 GB NVMe', 'n8n Pre-installed', '1,000 executions/month', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'n8n-Pro',
                'slug' => 'n8n-pro',
                'category' => 'n8n',
                'display_name' => 'n8n VPS Pro',
                'description' => 'For growing automation needs. Pre-installed n8n with 10,000 executions/month.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 160,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 3500.00,
                'cost_price' => 1400.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '160 GB NVMe', 'n8n Pre-installed', '10,000 executions/month', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Plesk VPS (2.5x pricing)
            [
                'name' => 'Plesk-Starter',
                'slug' => 'plesk-starter',
                'category' => 'plesk',
                'display_name' => 'Plesk VPS Starter',
                'description' => 'Web hosting made simple. Plesk Web Admin Edition included.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 100,
                'disk_type' => 'SSD',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 2250.00,
                'cost_price' => 900.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '100 GB SSD', 'Plesk Web Admin', '10 Domains', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Plesk-Business',
                'slug' => 'plesk-business',
                'category' => 'plesk',
                'display_name' => 'Plesk VPS Business',
                'description' => 'For web hosting businesses. Plesk Web Pro Edition included.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 200,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 4500.00,
                'cost_price' => 1800.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '200 GB NVMe', 'Plesk Web Pro', '30 Domains', 'WordPress Toolkit', 'Daily backup']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // cPanel VPS (2.5x pricing)
            [
                'name' => 'cPanel-Starter',
                'slug' => 'cpanel-starter',
                'category' => 'cpanel',
                'display_name' => 'cPanel VPS Starter',
                'description' => 'Centralized web hosting with industry-standard cPanel.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 100,
                'disk_type' => 'SSD',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 2750.00,
                'cost_price' => 1100.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '100 GB SSD', 'cPanel & WHM', '5 cPanel Accounts', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'cPanel-Business',
                'slug' => 'cpanel-business',
                'category' => 'cpanel',
                'display_name' => 'cPanel VPS Business',
                'description' => 'For hosting resellers. More accounts and resources.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 200,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 5500.00,
                'cost_price' => 2200.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '200 GB NVMe', 'cPanel & WHM', '50 cPanel Accounts', 'Softaculous', 'Daily backup']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // WordPress VPS (2.5x pricing)
            [
                'name' => 'WP-Starter',
                'slug' => 'wp-starter',
                'category' => 'wordpress',
                'display_name' => 'WordPress VPS Starter',
                'description' => 'Customizable and scalable server optimized for WordPress.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 80,
                'disk_type' => 'NVMe',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 1625.00,
                'cost_price' => 650.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '80 GB NVMe', 'WordPress Pre-installed', 'LiteSpeed Cache', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'WP-Business',
                'slug' => 'wp-business',
                'category' => 'wordpress',
                'display_name' => 'WordPress VPS Business',
                'description' => 'High-performance WordPress hosting for businesses.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 160,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 3250.00,
                'cost_price' => 1300.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '160 GB NVMe', 'WordPress + WooCommerce', 'Object Cache Pro', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'WP-Enterprise',
                'slug' => 'wp-enterprise',
                'category' => 'wordpress',
                'display_name' => 'WordPress VPS Enterprise',
                'description' => 'Ultimate WordPress performance for high-traffic sites.',
                'cpu_cores' => 16,
                'memory_gb' => 32,
                'disk_gb' => 320,
                'disk_type' => 'NVMe',
                'bandwidth' => '2 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 6500.00,
                'cost_price' => 2600.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['16 vCores', '32 GB RAM', '320 GB NVMe', 'WordPress Enterprise', 'Redis Object Cache', 'CDN Ready', 'Daily backup']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('vps_plans')->insert($plans);

        $this->command->info('✅ VPS Plans seeded successfully! Total: ' . count($plans) . ' plans');
    }
}
