<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Add specialized VPS plans for other categories
        $plans = [
            // n8n VPS - Automation focused
            [
                'name' => 'n8n-Starter',
                'slug' => 'n8n-starter',
                'category' => 'n8n',
                'display_name' => 'n8n VPS Starter',
                'description' => 'Perfect for workflow automation beginners. Pre-installed n8n with 1,000 executions/month.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 80,
                'disk_type' => 'NVMe',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 1750.00,
                'cost_price' => 700.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '80 GB NVMe', 'n8n Pre-installed', '1,000 executions/month', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'n8n-Pro',
                'slug' => 'n8n-pro',
                'category' => 'n8n',
                'display_name' => 'n8n VPS Pro',
                'description' => 'For growing automation needs. Pre-installed n8n with 10,000 executions/month.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 160,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 3500.00,
                'cost_price' => 1400.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '160 GB NVMe', 'n8n Pre-installed', '10,000 executions/month', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
            ],
            
            // Plesk VPS - Web hosting control panel
            [
                'name' => 'Plesk-Starter',
                'slug' => 'plesk-starter',
                'category' => 'plesk',
                'display_name' => 'Plesk VPS Starter',
                'description' => 'Web hosting made simple. Plesk Web Admin Edition included.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 100,
                'disk_type' => 'SSD',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 2250.00,
                'cost_price' => 900.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '100 GB SSD', 'Plesk Web Admin', '10 Domains', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'Plesk-Business',
                'slug' => 'plesk-business',
                'category' => 'plesk',
                'display_name' => 'Plesk VPS Business',
                'description' => 'For web hosting businesses. Plesk Web Pro Edition included.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 200,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 4500.00,
                'cost_price' => 1800.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '200 GB NVMe', 'Plesk Web Pro', '30 Domains', 'WordPress Toolkit', 'Daily backup']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
            ],
            
            // cPanel VPS - Industry standard
            [
                'name' => 'cPanel-Starter',
                'slug' => 'cpanel-starter',
                'category' => 'cpanel',
                'display_name' => 'cPanel VPS Starter',
                'description' => 'Centralized web hosting with industry-standard cPanel.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 100,
                'disk_type' => 'SSD',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 2750.00,
                'cost_price' => 1100.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '100 GB SSD', 'cPanel & WHM', '5 cPanel Accounts', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'cPanel-Business',
                'slug' => 'cpanel-business',
                'category' => 'cpanel',
                'display_name' => 'cPanel VPS Business',
                'description' => 'For hosting resellers. More accounts and resources.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 200,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 5500.00,
                'cost_price' => 2200.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '200 GB NVMe', 'cPanel & WHM', '50 cPanel Accounts', 'Softaculous', 'Daily backup']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
            ],
            
            // WordPress VPS - Optimized for WP
            [
                'name' => 'WP-Starter',
                'slug' => 'wp-starter',
                'category' => 'wordpress',
                'display_name' => 'WordPress VPS Starter',
                'description' => 'Customizable and scalable server optimized for WordPress.',
                'cpu_cores' => 4,
                'memory_gb' => 8,
                'disk_gb' => 80,
                'disk_type' => 'NVMe',
                'bandwidth' => '500 Mbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 1625.00,
                'cost_price' => 650.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['4 vCores', '8 GB RAM', '80 GB NVMe', 'WordPress Pre-installed', 'LiteSpeed Cache', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'WP-Business',
                'slug' => 'wp-business',
                'category' => 'wordpress',
                'display_name' => 'WordPress VPS Business',
                'description' => 'High-performance WordPress hosting for businesses.',
                'cpu_cores' => 8,
                'memory_gb' => 16,
                'disk_gb' => 160,
                'disk_type' => 'NVMe',
                'bandwidth' => '1 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 3250.00,
                'cost_price' => 1300.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['8 vCores', '16 GB RAM', '160 GB NVMe', 'WordPress + WooCommerce', 'Object Cache Pro', 'Daily backup', 'Unlimited traffic']),
                'is_active' => true,
                'is_sold_out' => false,
                'is_recommended' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'WP-Enterprise',
                'slug' => 'wp-enterprise',
                'category' => 'wordpress',
                'display_name' => 'WordPress VPS Enterprise',
                'description' => 'Ultimate WordPress performance for high-traffic sites.',
                'cpu_cores' => 16,
                'memory_gb' => 32,
                'disk_gb' => 320,
                'disk_type' => 'NVMe',
                'bandwidth' => '2 Gbps public',
                'unlimited_traffic' => true,
                'daily_backup' => true,
                'price_monthly' => 6500.00,
                'cost_price' => 2600.00,
                'setup_fee' => 0,
                'installation_free' => true,
                'features' => json_encode(['16 vCores', '32 GB RAM', '320 GB NVMe', 'WordPress Enterprise', 'Redis Object Cache', 'CDN Ready', 'Daily backup']),
                'is_active' => true,
                'is_sold_out' => false,
                'sort_order' => 3,
            ],
        ];

        DB::table('vps_plans')->insert($plans);
    }

    public function down(): void
    {
        // Remove specialized plans
        DB::table('vps_plans')
            ->whereIn('category', ['n8n', 'plesk', 'cpanel', 'wordpress'])
            ->delete();
    }
};
