{{-- FORM PAGE 4 : Applicant declaration 1-23, photo & signature boxes --}}
<div class="fpage">
  <div class="bar"><span>Applicant Declaration</span></div>
  <div class="two-col">
    <p><b>1.</b> I/We hereby declare that the details furnished above are true and correct to the best of my/our knowledge and belief and I/We undertake to inform you of any changes therein, immediately. In case any of the information is found to be false or untrue or misleading or misrepresenting, I/we am/are aware that I/we may be held liable for it.</p>
    <p><b>2.</b> I/We certify that I/we have the capacity to sign for the entity as per the CBDT rules/RBI guidelines.</p>
    <p><b>3.</b> I/We certify and declare that The Company does belong to the class of companies specified in sub-rule (2) of the Companies Rules 2017 (Restrictions on number of Layers) and it (Company) does not have more than two layers of subsidiaries.(As per the details given in Ministry of Corporate Affairs, Gazette notification No. 793 dated 21st Sept 2017.</p>
    <p><b>4.</b> I/We affirm and declare that I/We have read over and understood the rules and regulations of the Punjab National&nbsp;Bank (“Bank”) and those relating to various services offered by the Bank including but not limiting to debit card/internet banking/ Mobile Banking/ whatsapp Banking/Virtual Banking and any other facilities. I / We agree to abide by the same as amended/modified from time to time by the Bank/Regulator/ Government published through circulars, notifications, notice board/ websites/ newspaper publications, etc. I/We waive the rights ,if any, to have personal notice in respect of such amendments/ modifications. I/We agree that the transactions and requests executed in my/our account(s) by me / authorized person through internet, mobile, telebanking or virtual banking under my/our User ID and password/PIN/OTP will be legally binding on me/us &amp; I/We am/are responsible for the maintenance of secrecy and confidentiality of the authentication credentials and any other information/ details / OTP / PIN etc.,in such matters. I/We agree that Bank has got all the rights to debit my/our account for any scheme guidelines and service charge, expenses or other dues which the Bank is entitled/ liable to recover from me/us. I/We also authorize the Bank and agree to close/discontinue my account without any notice to me in case of any violation of laws/rules/ regulations or terms and conditions of maintaining the account. I/We hereby undertake to inform the Bank on any change in my communication address or constitution, and I/We shall submit the address proof in case of transfer of my account from one branch to another branch.</p>
    <p><b>5</b> I/We hereby, give my consent to download my KYC Records from the Central KYC Registry (CKYCR), only for the purpose of verification of my identity and address from the database of CKYCR Registry. I understand that my KYC record include my KYC record/personal information such as my name/address, date of birth, PAN no. etc.</p>
    <p><b>6.</b> In respect of accounts opened on the basis of Aadhaar details, I hereby declare that I have submitted the Aadhaar Card issued by UIDAI for identification and / or address proof towards the compliance of KYC norms under the PMLA , 2002 and I hereby agree that the Bank may verify the same with UIDAI and authorise the UIDAI expressly to release the identity and address through biometric authentication to the Bank.</p>
    <p><b>7.</b> I/We confirm and declare that I/We am/are not prevented/prohibited/restricted by any applicable legal/regulatory/contractual or other provisions from opening and/or maintaining the accounts or to transact with the Bank in any other way.</p>
    <p><b>8.</b> I/We agree that my/our personal KYC details may be shared with Central KYC registry or any other competent authority. I/We hereby consent to receive information from the Bank/Central KYC Registry/GoI/RBI or any other authority through SMS/e-mail on my registered mobile number/ e-mail address. I/We also agree that the non-receipt of any such SMS/e-mail shall not make the Bank liable for any loss or damage whatsoever in nature.</p>
    <p><b>9.</b> I/We hereby certify that I/We have declared my status as per the rules applicable under section 285BA of the Income Tax Act, 1961 as notified by Central Board of Direct Taxes (CBDT) vide Notification No. S.O. 2155(E) dated 7 August 2015 and RBI Circular Ref No. DBR.AML.BC.No.36/ 14.01.001/2015-16 dated 28 August 2015 in the matter including any subsequent modification/amendment thereof.</p>
    <p><b>10.</b> I/We understand, acknowledge and authorize that as per the provisions of Income Tax Act, Rules made thereunder and the guidelines issued by the Government/RBI in the matter, depending upon the residential status and/or other criteria stipulated therein, the Bank may have to report the details in respect of my/our account(s) as per the prescribed format to the Central Board of Direct Taxes (CBDT) or other Government Agencies to comply with the obligations as per the Inter- Governmental Agreements (IGA) in respect of Foreign Accounts Tax Compliance Act (FATCA) and Common Reporting Standards (CRS) and / or any other similar arrangements.</p>
    <p><b>11.</b> I/We certify &amp; declare that the information provided by me/us for opening account and availing other services herein or through website/electronically as applicable to me/us and signed/authenticated by me/us as well as in the documentary evidence provided by me/us for opening account and availing other services are, to the best of my/our knowledge and belief, true, correct and complete and that I/We have not withheld any material information that may affect the assessment/categorization of my/our account as a U.S. Reportable Account or Other Reportable Account or otherwise. In case any of the information or details provided by me/us is found to be false or untrue or misleading or misrepresenting, I/We am/are aware that I/We may be held liable for it.</p>
    <p><b>12.</b> I/We undertake the responsibility to declare and disclose immediately and in no case beyond 30 days from the date of change, any changes that may take place in the information provided herein/or otherwise, as well as in the documentary evidence provided by me or if any certification becomes incorrect or undergoes a change. I further undertake to provide fresh and valid self-certification along with documentary evidence as and when so required; nevertheless all declaration and undertaking given herein will also be applicable to all such modified/amended documents/information provided by me unless revised self-certification as above is provided to the Bank.</p>
    <p><b>13.</b> I/We also agree that my/our failure to disclose any material fact/information known to me/us now or in future or my/our failure to remedy any deficiency in documents/ information/other details within the stipulated period, may invalidate me/us from transacting in the account and the Bank would be within its right to put restrictions in the operations of my account or to close it or to report to any regulator and/or any authority designated by the Government of India (GoI)/RBI for the said purpose or take any other action as may be deemed appropriate by the Bank under the guidelines issued by CBDT/RBI/GoI from time to time.</p>
    <p><b>14.</b> I/We also agree to furnish and intimate to the Bank any other particulars that are called upon me/us to provide on account of any change in law either in India or abroad in relating to the operation or maintenance of the account.</p>
    <p><b>15.</b> I/We shall indemnify the Bank from any loss/damage that may be caused to the Bank on account of any defect/mistake in the details provided herein or on account of providing incorrect or incomplete information by me/us.</p>
    <p><b>16.</b> I/We undertake to submit data/information together with fresh KYC documents for updation of KYC details at periodical intervals as may be required by the Bank.</p>
    <p><b>17.</b> I/We understand that the account will be activated and debits will be allowed only after completion of Customer Due Diligence relating to KYC by the Bank.</p>
    <p><b>18.</b> I/We have been advised of Quarterly average/minimum balance requirement for the account to be opened and given to understand that these requirements are subject to revision/change and such revision/changes will be uploaded in the Bank’s site which will be acceptable to me as a notice to that effect.</p>
    <p><b>19.</b> I/We Undertake to submit Aadhaar and / or PAN within 6 months from the date of opening of account , failing to which I understand my account will cease to be operational as per GOI guidelines, amending Prevention of Money laundering (Maintenance of Records ) Rules 2005.(In case the account is opened without Aadhaar / PAN)</p>
    <p><b>20.</b> In case, deemed OVDs are submitted for current address at the time of Account opening, I undertake to submit Aadhaar or any of the OVD having Current Address within 3 months from the date of account opening , failing to which I understand that my account may cease to be operational as per GOI guidelines at the material time.</p>
    <p><b>21.</b> I confirm and undertake that I will not deal in Virtual Currencies and will not use my account for any services related Virtual Currencies or facilitate any person or entity, in dealing with or settling virtual currencies.</p>
    <p><b>22.</b> I/we undertake to keep QAB/MAB (Quaterly/Monthly Average Balance) in the account as prescribed under the respective account scheme and agree to pay the penalty if QAB/MAB is not maintained.</p>
    <p><b>23.</b> I/we understand that registration of email ID and Mobile no. are subject to successful validation of email ID &amp; mobile number by me/us as per process prescribed by the bank, I/we will be able to use the product/services linked with email Id &amp; mobile number only after successful validation by me/us.</p>
  </div>

  <div class="row nowrap mt6">
    <span class="lbl">CIF No.</span><input class="cb" style="--n:8" maxlength="8" name="d_cif">
    <span class="grow"></span>
    <span class="lbl">A/C No.</span><input class="cb" style="--n:16" maxlength="16" name="d_ac">
  </div>
  <div class="lbl mt4">Mode of Operation<input class="ln" style="width:520px" name="mode_op"></div>

  <div class="flex mt4" style="justify-content:space-between">
    @foreach([1,2,3] as $i)
    <div class="col" style="align-items:center;width:32%">
      <div class="photo" style="width:150px;height:160px">Please Paste<br>Photograph<br><br>Here<br><br>Signatory {{ $i }}</div>
      <div class="small center mt2">Signature of Authorized Signatory {{ $i }} (Do not overlap)</div>
      <div class="bordered" style="width:100%;height:90px;display:flex;flex-direction:column;justify-content:flex-end">
        <div class="small">Name:</div>
        <div class="small mt2">Designation:</div>
        <div class="small mt2">Date:</div>
      </div>
      <div class="bordered" style="width:100%;border-top:0;padding-top:4px"><span class="small">Name, Signature, Seal and GBPA/PF No. of verifying official</span></div>
    </div>
    @endforeach
  </div>

  <div class="pgnum">4</div>
</div>
